version: '3'
services:

  db-movie:
    volumes:
      - pg-data-movie:/var/lib/postgresql/data
    expose:
      - "5432"
    restart: always

  app-movie:
    build:
      target: prod
    volumes:
      - app-static:/app/static
      - app-media:/app/media
    env_file: .env.prod
    expose:
      - "8000"
    restart: always

  nginx-movie:
    container_name: nginx-movie
    build: nginx
    volumes:
      - ./nginx/config.d:/etc/nginx/config.d:ro
      - ./nginx/nginx.config:/etc/nginx/nginx.config:ro
      - app-static:/static
      - app-media:/media
    depends_on:
      - app-movie
    ports:
      - "80:80"
    restart: always

  es01:
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - es-data01:/usr/share/elasticsearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1

volumes:
  pg-data-movie:
  app-static:
  app-media:
  es-data01: